version: "3.7"
services:

  app:
    build: './app'
    ports:
      - "5000:5000"
    depends_on:
      - rabbit
    networks:
       - mlprovider

  rabbit:
    container_name: rabbitmq_host
    hostname: rabbit
    image: "rabbitmq:3-management"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
       - mlprovider

  mongodb_container:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    networks:
       - mlprovider
      
  worker:
    build: './worker'
    user: nobody
    depends_on:
      - rabbit
      - app
    networks:
       - mlprovider
networks:
  mlprovider:
     name: mlprovider

volumes:
  mongodb_data_container: 